const assetRoot='assets/current/';
const rooms=[
 {id:'living',name:'Гостиная',images:['living-05.jpg','living-01.jpg','living-02.jpg','living-03.jpg','living-04.jpg','living-06.jpg'],labels:['Диван · общий вид','Диван · текстиль и декор','Диван и журнальный столик','Вид от входа','Вид от ТВ-зоны','ТВ-зона']},
 {id:'kitchen',name:'Кухня и обеденная зона',images:['kitchen-01.jpg','kitchen-02.jpg','kitchen-03.jpg','kitchen-04.jpg','kitchen-05.jpg','kitchen-06.jpg'],labels:['Обеденная зона · стекло и свет','Обеденная зона и кухня','Кухня · общий вид','Подвесной светильник','Обеденная зона','Обеденная зона и ТВ-зона']},
 {id:'entry',name:'Входная зона',images:['entry-01.jpg','entry-02.jpg'],labels:['Вид от входной двери','Пуф и система хранения']},
 {id:'master',name:'Мастер-спальня',images:['master-01.jpg','master-02.jpg','master-03.jpg','master-04.jpg','master-05.jpg'],labels:['Кровать · общий вид','Вид на окно','Вид от окна','ТВ-консоль · вариант 2','ТВ-консоль · вариант 1']},
 {id:'bedroom',name:'Детская спальня',images:['bedroom-01.jpg','bedroom-02.jpg','bedroom-03.jpg','bedroom-04.jpg','bedroom-05.jpg','bedroom-06.jpg','bedroom-07.jpg'],labels:['Кровати · общий вид','Рабочая зона','Две кровати · вид на шкаф','Две кровати · вид на окно','Шкаф · альтернативный вариант','Двуспальная кровать · альтернативный вариант','Окно · альтернативный вариант']},
 {id:'master-bath',name:'Мастер-санузел',images:['master-bath-01.jpg','master-bath-02.jpg','master-bath-03.jpg','master-bath-04.jpg'],labels:['Раковина и зеркало','Ванна','Вид от ванны','Вид на дверь']},
 {id:'bath',name:'Санузел с душем',images:['bath-01.jpg','bath-02.jpg','bath-03.jpg','bath-04.jpg'],labels:['Раковина','Душевая зона','Вид от раковины','Вид от душевой']},
 {id:'wc',name:'Гостевой санузел',images:['wc-01.jpg','wc-02.jpg','wc-03.jpg','wc-04.jpg'],labels:['Раковина','Вид от двери','Вид от раковины','Вид на дверь']},
 {id:'terrace',name:'Концепция террасы',images:['terrace-01.png','terrace-02.png','terrace-03.png','terrace-04.jpg','terrace-05.jpg','terrace-06.jpg','terrace-07.jpg','terrace-08.jpg','terrace-09.jpg'],labels:['Приватная зона','Приватная зона · ракурс','Терраса · общий вид','Два кресла и хранение','Зона с креслами','Боковой вид','Терраса · ракурс 4','Терраса · ракурс 3','Терраса · ракурс 6']}
];
const defaults=['living-01.jpg','kitchen-01.jpg','master-01.jpg','master-bath-01.jpg'];
let favorites=new Set(defaults);
try{const saved=JSON.parse(localStorage.getItem('grove-client-favorites-v2'));if(Array.isArray(saved))favorites=new Set(saved.filter(f=>rooms.some(r=>r.images.includes(f))))}catch{}
let revealObserver,currentFilter='all';
const gallery=document.getElementById('gallery');
gallery.innerHTML=`<div class="room-filters" role="group" aria-label="Выбрать помещение"><button class="selected" data-filter="all" aria-pressed="true">Все помещения <sup>09</sup></button><button data-filter="favorites" aria-pressed="false">Избранное <sup id="favorite-count">${favorites.size}</sup></button>${rooms.map(r=>`<button data-filter="${r.id}" aria-pressed="false">${r.name}</button>`).join('')}</div><div class="gallery-note" aria-live="polite"></div><div class="room-grid"></div>`;
const label=(r,i)=>r.labels[i];
function renderGallery(filter=currentFilter){
 currentFilter=filter;
 const records=filter==='all'?rooms.map(r=>({r,index:0})):filter==='favorites'?rooms.flatMap(r=>r.images.map((f,index)=>({r,index})).filter(x=>favorites.has(x.r.images[x.index]))):rooms.find(r=>r.id===filter).images.map((_,index)=>({r:rooms.find(r=>r.id===filter),index}));
 const note=filter==='bedroom'?'На плане — две отдельные кровати. Альтернативные ракурсы с двуспальной кроватью подписаны отдельно.':filter==='master'?'Два варианта ТВ-консоли представлены в конце галереи.':filter==='favorites'?'Сохранённые кадры на этом устройстве. Добавляйте и убирайте их кнопкой с сердцем.':'Выберите помещение или откройте кадр. В галерее доступны все ракурсы и скачивание оригинала.';
 gallery.querySelector('.gallery-note').textContent=note;
 gallery.querySelector('.room-grid').innerHTML=records.length?records.map(({r,index},i)=>`<article class="room-card reveal" style="--delay:${i%3*70}ms"><div class="room-media"><button class="room-image" data-open-room="${r.id}" data-frame="${index}" aria-label="Открыть: ${r.name}, ${label(r,index)}"><img src="${assetRoot+r.images[index]}" alt="${r.name} — ${label(r,index)}" loading="lazy" decoding="async"><span class="image-badge">${String(filter==='all'?rooms.indexOf(r)+1:index+1).padStart(2,'0')}</span><span class="image-open">Открыть</span></button><button class="favorite-button ${favorites.has(r.images[index])?'is-saved':''}" data-favorite="${r.images[index]}" aria-label="${favorites.has(r.images[index])?'Убрать из':'Добавить в'} избранное: ${r.name}, ${label(r,index)}" aria-pressed="${favorites.has(r.images[index])}">♡</button></div><div class="room-caption"><h3>${r.name}</h3><span>${filter==='all'?r.images.length+' '+(r.images.length===2||r.images.length===4?'ракурса':'ракурсов'):String(index+1).padStart(2,'0')+' / '+r.images.length}</span></div>${filter!=='all'?`<p class="frame-label">${label(r,index)}</p>`:''}</article>`).join(''):'<div class="empty-favorites"><p>В избранном пока нет кадров.</p><button data-filter="all">Открыть помещения ↗</button></div>';
 document.getElementById('favorite-count').textContent=favorites.size;
 if(revealObserver)watchReveals();
}
function toggleFavorite(file){favorites.has(file)?favorites.delete(file):favorites.add(file);try{localStorage.setItem('grove-client-favorites-v2',JSON.stringify([...favorites]))}catch{}renderGallery();if(imageDialog.open)syncDialogFavorite()}
renderGallery();
const materials=[
 ['living-01.jpg','Молочный текстиль','Мягкая обивка, подушки и полупрозрачный тюль.','textile'],
 ['kitchen-01.jpg','Камень с прожилками','Светлая поверхность с тёплым рисунком.','stone'],
 ['master-01.jpg','Дерево','Тёмные стеновые панели и спокойная фактура.','wood'],
 ['master-bath-01.jpg','Светлая минеральная отделка','Матовые поверхности в санузлах.','mineral'],
 ['kitchen-01.jpg','Стекло и металл','Шампань, бронзовые оттенки и прозрачное стекло.','glass'],
 ['living-01.jpg','Тёплый тауп','Плотные шторы и акцентный текстиль.','taupe']
];
document.getElementById('concept').innerHTML=`<div class="section-heading"><span class="eyebrow">02 / МУДБОРД</span><h2>Материалы и цвет</h2><p>Подборка по визуализациям проекта. Текстиль, дерево, светлый камень и стекло.</p></div><div class="concept-board"><button class="concept-photo wide reveal" data-open-room="living" data-frame="1" aria-label="Открыть кадр гостиной из мудборда"><img src="${assetRoot}living-01.jpg" alt="Молочная обивка, тауп и светлый камень" loading="lazy"><span class="board-caption">01 / ТЕКСТИЛЬ · КАМЕНЬ</span></button><button class="concept-photo tall reveal" data-open-room="kitchen" data-frame="0" aria-label="Открыть кадр обеденной зоны из мудборда"><img src="${assetRoot}kitchen-01.jpg" alt="Скульптурный светильник и стекло оттенка шампань" loading="lazy"><span class="board-caption">02 / СТЕКЛО · СВЕТ</span></button><button class="concept-photo reveal" data-open-room="master" data-frame="0" aria-label="Открыть кадр мастер-спальни из мудборда"><img src="${assetRoot}master-01.jpg" alt="Тёмное дерево и светлый текстиль мастер-спальни" loading="lazy"><span class="board-caption">03 / ДЕРЕВО</span></button><button class="concept-photo reveal" data-open-room="master-bath" data-frame="0" aria-label="Открыть кадр мастер-санузла из мудборда"><img src="${assetRoot}master-bath-01.jpg" alt="Минеральная отделка и деревянная мебель санузла" loading="lazy"><span class="board-caption">04 / МИНЕРАЛЬНАЯ ОТДЕЛКА</span></button></div><div class="palette">${[['#E8E1D8','Молочный'],['#C5B7A5','Песочный'],['#8B7B6E','Тауп'],['#504034','Тёмное дерево'],['#B29A77','Шампань'],['#252321','Графит']].map(([c,n],i)=>`<div class="reveal" style="--delay:${i*60}ms"><i style="background:${c}"></i><span>${n}<small>${c}</small></span></div>`).join('')}</div><div class="material-grid">${materials.map(([f,n,t,c],i)=>`<article class="material-card reveal"><div class="texture-sample ${c}"><img src="${assetRoot+f}" alt="Фрагмент визуализации: ${n}" loading="lazy"></div><div><span class="eyebrow">0${i+1}</span><h3>${n}</h3><p>${t}</p></div></article>`).join('')}</div><p class="material-note">Оттенки ориентировочные. Фактуры показаны фрагментами рендеров; конкретные покрытия и артикулы подбираются по образцам.</p>`;
const driveRoot='https://drive.google.com/drive/folders/13KfT93hW29qi-RcfXrxmaT4wx7pcZht7';
const driveVisuals='https://drive.google.com/drive/folders/12mCrk6UnyjmN50mqCO5ORmmmCSI50shQ';
const drivePlan='https://drive.google.com/file/d/1e_u4FcyxiXBrnR8vyR1Lb0NoIuT4We5b/view';
document.getElementById('documents').innerHTML=`<div class="section-heading"><span class="eyebrow">03 / ПЛАНИРОВКА</span><h2>План мебели</h2><p>Актуальный файл из проекта на Google Диске. Обновлён 8 октября 2026.</p></div><div class="drawing-layout"><button class="plan-preview" data-plan aria-label="Увеличить план расстановки мебели"><img src="${assetRoot}furniture-plan.png" alt="План квартиры с расстановкой мебели" loading="lazy"><span>Увеличить план <b>↗</b></span></button><div class="drawing-aside"><span class="eyebrow">GROVE 2 / 01 ЛИСТ</span><h3>Расстановка мебели</h3><p>Кухня и обеденная зона, гостиная, две спальни, входная зона, санузлы и терраса.</p><button class="solid-button" data-plan>Рассмотреть план <span>Увеличение и перемещение</span></button><a class="text-link" href="${assetRoot}furniture-plan.pdf" download="GROVE-2-план-мебели.pdf">Скачать PDF <span>ОРИГИНАЛ ↗</span></a><a class="text-link" href="${drivePlan}" target="_blank" rel="noopener">Открыть на Google Диске <span>↗</span></a><p class="plan-source-note">План служит для согласования планировочного решения — согласно примечанию в исходном файле.</p></div></div>`;
document.getElementById('contacts').innerHTML=`<div class="contact-panel"><div><span class="eyebrow">04 / ПРОЕКТ</span><h2>Файлы проекта</h2><span class="contact-project">GROVE 2</span></div><div class="contact-details"><div><span>Google Диск</span><a class="text-link" href="${driveRoot}" target="_blank" rel="noopener">Папка проекта <span>↗</span></a></div><div><span>Все актуальные визуализации</span><a class="text-link" href="${driveVisuals}" target="_blank" rel="noopener">Оригиналы изображений <span>↗</span></a></div><div><span>Планировка</span><a class="text-link" href="${drivePlan}" target="_blank" rel="noopener">План расстановки мебели <span>↗</span></a></div></div></div>`;
document.body.insertAdjacentHTML('beforeend',`<dialog id="image-dialog" class="image-dialog" aria-labelledby="image-dialog-title"><div class="dialog-top"><div><span class="eyebrow">GROVE 2 / ВИЗУАЛИЗАЦИИ</span><h2 id="image-dialog-title"></h2><p id="dialog-label"></p></div><button class="close-dialog" aria-label="Закрыть галерею">×</button></div><img id="dialog-image" alt=""><div class="dialog-bottom"><button id="prev-image" aria-label="Предыдущий ракурс">← Назад</button><span id="image-counter"></span><button id="next-image" aria-label="Следующий ракурс">Далее →</button><button id="dialog-favorite" aria-pressed="false">♡ В избранное</button><a id="image-download" download>Скачать оригинал ↗</a></div><div id="room-thumbs" class="room-thumbs"></div></dialog><dialog id="plan-dialog" class="plan-dialog" aria-labelledby="plan-title"><div class="dialog-top"><div><span class="eyebrow">GROVE 2 / 08.10.2026</span><h2 id="plan-title">План расстановки мебели</h2></div><button class="close-dialog" aria-label="Закрыть план">×</button></div><div class="plan-toolbar"><div class="zoom-controls"><button id="zoom-out" aria-label="Уменьшить план">−</button><output id="zoom-level" aria-live="polite">100%</output><button id="zoom-in" aria-label="Увеличить план">+</button><button id="zoom-reset">Весь план</button></div><a href="${assetRoot}furniture-plan.pdf" download="GROVE-2-план-мебели.pdf">Скачать PDF ↗</a></div><div class="plan-canvas" tabindex="0" aria-label="План мебели. Используйте кнопки увеличения и прокрутку для перемещения."><img src="${assetRoot}furniture-plan.png" alt="Актуальный план расстановки мебели GROVE 2"></div><p class="pdf-note">Увеличьте план кнопкой «+». Для перемещения прокручивайте изображение.</p></dialog>`);
const imageDialog=document.getElementById('image-dialog'),planDialog=document.getElementById('plan-dialog');let currentRoom=rooms[0],currentImage=0,planZoom=1;
function syncDialogFavorite(){const b=document.getElementById('dialog-favorite'),saved=favorites.has(currentRoom.images[currentImage]);b.textContent=saved?'♥ В избранном':'♡ В избранное';b.setAttribute('aria-pressed',saved)}
function showImage(){const src=assetRoot+currentRoom.images[currentImage];document.getElementById('image-dialog-title').textContent=currentRoom.name;document.getElementById('dialog-label').textContent=label(currentRoom,currentImage);const im=document.getElementById('dialog-image');im.classList.remove('frame-enter');im.onload=()=>im.classList.add('frame-enter');im.src=src;im.alt=currentRoom.name+' — '+label(currentRoom,currentImage);document.getElementById('image-counter').textContent=`${String(currentImage+1).padStart(2,'0')} / ${String(currentRoom.images.length).padStart(2,'0')}`;const download=document.getElementById('image-download');download.href=src;download.download=currentRoom.images[currentImage];document.getElementById('room-thumbs').innerHTML=currentRoom.images.map((f,i)=>`<button data-thumb="${i}" class="${i===currentImage?'selected':''}" aria-label="${label(currentRoom,i)}" aria-pressed="${i===currentImage}"><img src="${assetRoot+f}" alt="" loading="lazy"></button>`).join('');syncDialogFavorite()}
function zoomPlan(value){planZoom=Math.max(1,Math.min(4,value));document.querySelector('.plan-canvas img').style.width=planZoom*100+'%';document.getElementById('zoom-level').textContent=Math.round(planZoom*100)+'%';document.getElementById('zoom-out').disabled=planZoom===1;document.getElementById('zoom-in').disabled=planZoom===4}
document.addEventListener('click',e=>{
 const f=e.target.closest('[data-filter]');if(f){document.querySelectorAll('.room-filters [data-filter]').forEach(b=>{b.classList.toggle('selected',b.dataset.filter===f.dataset.filter);b.setAttribute('aria-pressed',b.dataset.filter===f.dataset.filter)});renderGallery(f.dataset.filter)}
 const saved=e.target.closest('[data-favorite]');if(saved)toggleFavorite(saved.dataset.favorite);
 const r=e.target.closest('[data-open-room]');if(r){currentRoom=rooms.find(x=>x.id===r.dataset.openRoom);currentImage=Number(r.dataset.frame||0);showImage();imageDialog.showModal();document.body.classList.add('modal-open')}
 const t=e.target.closest('[data-thumb]');if(t){currentImage=Number(t.dataset.thumb);showImage()}
 if(e.target.closest('[data-plan]')){zoomPlan(1);planDialog.showModal();document.querySelector('.plan-canvas').scrollTo(0,0);document.body.classList.add('modal-open')}
 if(e.target.closest('.close-dialog'))e.target.closest('dialog').close();
});
document.getElementById('dialog-favorite').onclick=()=>toggleFavorite(currentRoom.images[currentImage]);
document.getElementById('zoom-in').onclick=()=>zoomPlan(planZoom+.5);document.getElementById('zoom-out').onclick=()=>zoomPlan(planZoom-.5);document.getElementById('zoom-reset').onclick=()=>{zoomPlan(1);document.querySelector('.plan-canvas').scrollTo(0,0)};
document.getElementById('prev-image').onclick=()=>{currentImage=(currentImage-1+currentRoom.images.length)%currentRoom.images.length;showImage()};document.getElementById('next-image').onclick=()=>{currentImage=(currentImage+1)%currentRoom.images.length;showImage()};
imageDialog.addEventListener('keydown',e=>{if(e.key==='ArrowRight'){e.preventDefault();document.getElementById('next-image').click()}if(e.key==='ArrowLeft'){e.preventDefault();document.getElementById('prev-image').click()}});
for(const d of [imageDialog,planDialog]){d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close()}});d.addEventListener('close',()=>document.body.classList.remove('modal-open'))}
const reducedMotion=window.matchMedia('(prefers-reduced-motion: reduce)');
function watchReveals(){document.querySelectorAll('.reveal:not(.is-visible)').forEach(e=>revealObserver.observe(e))}
if(!reducedMotion.matches&&'IntersectionObserver' in window){document.body.classList.add('motion-enabled');revealObserver=new IntersectionObserver(entries=>entries.forEach(({target,isIntersecting})=>{if(isIntersecting){target.classList.add('is-visible');revealObserver.unobserve(target)}}),{threshold:.08});document.querySelectorAll('.section-heading,.drawing-layout,.contact-panel').forEach(e=>e.classList.add('reveal'));watchReveals()}
reducedMotion.addEventListener('change',()=>{if(reducedMotion.matches)document.body.classList.remove('motion-enabled')});
const coverImage=document.querySelector('.hero-image'),heroFrames=[['cover-01.jpg','01 / КУХНЯ И ОБЕДЕННАЯ ЗОНА','Кухня и обеденная зона — люстра и декор, вид от кухни GROVE 2'],['cover-02.jpg','02 / ГОСТИНАЯ','Диван и журнальный столик GROVE 2'],['cover-03.jpg','03 / МАСТЕР-СПАЛЬНЯ','Мастер-спальня GROVE 2'],['cover-04.jpg','04 / МАСТЕР-САНУЗЕЛ','Мастер-санузел GROVE 2']];let heroVersion=0;
document.querySelectorAll('[data-hero]').forEach(b=>b.addEventListener('click',()=>{const [file,caption,alt]=heroFrames[Number(b.dataset.hero)],version=++heroVersion,preloaded=new Image();preloaded.onload=()=>{if(version!==heroVersion)return;coverImage.src=preloaded.src;coverImage.alt=alt;coverImage.classList.remove('hero-fade');requestAnimationFrame(()=>coverImage.classList.add('hero-fade'));document.getElementById('hero-caption').textContent=caption;document.querySelectorAll('[data-hero]').forEach(c=>{c.classList.toggle('active',c===b);c.setAttribute('aria-pressed',c===b)})};preloaded.src=assetRoot+file}));
let ticking=false;function updateScroll(){const max=document.documentElement.scrollHeight-innerHeight;document.querySelector('.scroll-progress').style.transform=`scaleX(${max>0?scrollY/max:0})`;if(!reducedMotion.matches){const rect=document.querySelector('.cover').getBoundingClientRect();if(rect.bottom>0&&rect.top<innerHeight){const shift=Math.max(-22,Math.min(22,-rect.top*.045));document.querySelector('.cover-project').style.transform=`translateY(${shift}px)`}}ticking=false}
window.addEventListener('scroll',()=>{if(!ticking){requestAnimationFrame(updateScroll);ticking=true}},{passive:true});updateScroll();
imageDialog.addEventListener('touchstart',e=>{imageDialog.dataset.touchX=e.changedTouches[0].screenX},{passive:true});imageDialog.addEventListener('touchend',e=>{if(e.target.closest('button,a,.room-thumbs'))return;const delta=e.changedTouches[0].screenX-Number(imageDialog.dataset.touchX);if(Math.abs(delta)>65)document.getElementById(delta<0?'next-image':'prev-image').click()},{passive:true});

// Pointer effects only run while a mouse is active; touch and reduced motion stay native.
const finePointer=matchMedia('(hover:hover) and (pointer:fine)');
const cursor=document.createElement('div');cursor.className='art-cursor';cursor.setAttribute('aria-hidden','true');cursor.innerHTML='<span></span>';document.body.append(cursor);
let pointerX=innerWidth/2,pointerY=innerHeight/2,cursorX=pointerX,cursorY=pointerY,cursorFrame=0,cursorActive=false;
function cursorLoop(){cursorX+=(pointerX-cursorX)*.18;cursorY+=(pointerY-cursorY)*.18;cursor.style.transform=`translate3d(${cursorX}px,${cursorY}px,0)`;if(cursorActive)cursorFrame=requestAnimationFrame(cursorLoop);}
function stopCursor(){cursorActive=false;cancelAnimationFrame(cursorFrame);document.body.classList.remove('custom-pointer');cursor.classList.remove('shown');document.querySelectorAll('.pointer-shift').forEach(el=>{el.style.translate='';el.classList.remove('pointer-shift')});document.querySelectorAll('.pointer-image').forEach(el=>{el.style.removeProperty('--pointer-x');el.style.removeProperty('--pointer-y');el.classList.remove('pointer-image')});}
document.addEventListener('pointermove',e=>{
 if(e.pointerType!=='mouse'||!finePointer.matches||reducedMotion.matches)return;
 pointerX=e.clientX;pointerY=e.clientY;
 if(!cursorActive){cursorX=pointerX;cursorY=pointerY;cursorActive=true;cursorLoop();}
 document.body.classList.add('custom-pointer');cursor.classList.add('shown');
 const image=e.target.closest('.room-image,.concept-photo');const control=e.target.closest('a,button,summary');
 cursor.classList.toggle('over-image',!!image);cursor.classList.toggle('over-control',!!control&&!image);cursor.querySelector('span').textContent=image?'Смотреть':'';
 if(image){const box=image.getBoundingClientRect();image.classList.add('pointer-image');image.style.setProperty('--pointer-x',`${(e.clientX-box.left-box.width/2)*.015}px`);image.style.setProperty('--pointer-y',`${(e.clientY-box.top-box.height/2)*.015}px`);}
 const magnetic=e.target.closest('.hero-controls button,.audience button,.solid-button,.brand-mark');
 if(magnetic){const b=magnetic.getBoundingClientRect();magnetic.classList.add('pointer-shift');magnetic.style.translate=`${(e.clientX-b.left-b.width/2)*.13}px ${(e.clientY-b.top-b.height/2)*.2}px`;}
},{passive:true});
document.addEventListener('pointerout',e=>{const shifted=e.target.closest('.pointer-shift');if(shifted&&!shifted.contains(e.relatedTarget)){shifted.style.translate='';shifted.classList.remove('pointer-shift')}const image=e.target.closest('.pointer-image');if(image&&!image.contains(e.relatedTarget)){image.style.removeProperty('--pointer-x');image.style.removeProperty('--pointer-y');image.classList.remove('pointer-image')}});
document.documentElement.addEventListener('pointerleave',stopCursor);window.addEventListener('blur',stopCursor);finePointer.addEventListener('change',stopCursor);reducedMotion.addEventListener('change',stopCursor);
document.addEventListener('pointerdown',()=>cursor.classList.add('pressed'));document.addEventListener('pointerup',()=>cursor.classList.remove('pressed'));
document.querySelectorAll('.section-heading h2,.contact-panel h2').forEach(h=>{h.classList.add('editorial-title');h.innerHTML=h.textContent.trim().split(' ').map((word,i)=>`<span style="--word-delay:${i*90}ms">${word}</span>`).join(' ')});
const headingObserver=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('heading-visible');headingObserver.unobserve(e.target)}}),{threshold:.25});document.querySelectorAll('.editorial-title').forEach(h=>headingObserver.observe(h));
if(!reducedMotion.matches){const imageObserver=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('image-revealed');imageObserver.unobserve(e.target)}}),{threshold:.12});const observeImages=()=>document.querySelectorAll('.room-image:not(.image-revealed),.concept-photo:not(.image-revealed)').forEach(el=>imageObserver.observe(el));observeImages();new MutationObserver(observeImages).observe(gallery.querySelector('.room-grid'),{childList:true});}
